# Generated by Django 3.1.5 on 2021-01-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='localization',
            field=models.ForeignKey(default='Warszawa', on_delete=django.db.models.deletion.CASCADE, to='content.city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(default='Ogólna', on_delete=django.db.models.deletion.CASCADE, to='content.type'),
        ),
    ]
