# Generated by Django 3.1.5 on 2021-01-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.FileField(default='default.pdf', upload_to='schedule/'),
        ),
    ]
