# Generated by Django 3.1.5 on 2021-01-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_event_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
